/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as ClockQrTokenRouteImport } from './routes/clock.$qrToken'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed.welcome'
import { Route as AuthedWarehouseRouteImport } from './routes/_authed.warehouse'
import { Route as AuthedStockRouteImport } from './routes/_authed.stock'
import { Route as AuthedShiftsRouteImport } from './routes/_authed.shifts'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedSalesRouteImport } from './routes/_authed.sales'
import { Route as AuthedRotaRouteImport } from './routes/_authed.rota'
import { Route as AuthedOrdersRouteImport } from './routes/_authed.orders'
import { Route as AuthedMyRouteImport } from './routes/_authed.my'
import { Route as AuthedMenuRouteImport } from './routes/_authed.menu'
import { Route as AuthedInsightsRouteImport } from './routes/_authed.insights'
import { Route as AuthedPeopleIndexRouteImport } from './routes/_authed.people.index'
import { Route as AuthedPeopleMemberIdRouteImport } from './routes/_authed.people.$memberId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ClockQrTokenRoute = ClockQrTokenRouteImport.update({
  id: '/clock/$qrToken',
  path: '/clock/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWarehouseRoute = AuthedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShiftsRoute = AuthedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesRoute = AuthedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRotaRoute = AuthedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersRoute = AuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRoute = AuthedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMenuRoute = AuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInsightsRoute = AuthedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleIndexRoute = AuthedPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleMemberIdRoute = AuthedPeopleMemberIdRouteImport.update({
  id: '/people/$memberId',
  path: '/people/$memberId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/insights': typeof AuthedInsightsRoute
  '/menu': typeof AuthedMenuRoute
  '/my': typeof AuthedMyRoute
  '/orders': typeof AuthedOrdersRoute
  '/rota': typeof AuthedRotaRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/stock': typeof AuthedStockRoute
  '/warehouse': typeof AuthedWarehouseRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/insights': typeof AuthedInsightsRoute
  '/menu': typeof AuthedMenuRoute
  '/my': typeof AuthedMyRoute
  '/orders': typeof AuthedOrdersRoute
  '/rota': typeof AuthedRotaRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/stock': typeof AuthedStockRoute
  '/warehouse': typeof AuthedWarehouseRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/': typeof AuthedIndexRoute
  '/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/people': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/insights': typeof AuthedInsightsRoute
  '/_authed/menu': typeof AuthedMenuRoute
  '/_authed/my': typeof AuthedMyRoute
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/rota': typeof AuthedRotaRoute
  '/_authed/sales': typeof AuthedSalesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/shifts': typeof AuthedShiftsRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/_authed/warehouse': typeof AuthedWarehouseRoute
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/_authed/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/insights'
    | '/menu'
    | '/my'
    | '/orders'
    | '/rota'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/stock'
    | '/warehouse'
    | '/welcome'
    | '/clock/$qrToken'
    | '/people/$memberId'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/insights'
    | '/menu'
    | '/my'
    | '/orders'
    | '/rota'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/stock'
    | '/warehouse'
    | '/welcome'
    | '/clock/$qrToken'
    | '/'
    | '/people/$memberId'
    | '/people'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/insights'
    | '/_authed/menu'
    | '/_authed/my'
    | '/_authed/orders'
    | '/_authed/rota'
    | '/_authed/sales'
    | '/_authed/settings'
    | '/_authed/shifts'
    | '/_authed/stock'
    | '/_authed/warehouse'
    | '/_authed/welcome'
    | '/clock/$qrToken'
    | '/_authed/'
    | '/_authed/people/$memberId'
    | '/_authed/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClockQrTokenRoute: typeof ClockQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/clock/$qrToken': {
      id: '/clock/$qrToken'
      path: '/clock/$qrToken'
      fullPath: '/clock/$qrToken'
      preLoaderRoute: typeof ClockQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/warehouse': {
      id: '/_authed/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthedWarehouseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shifts': {
      id: '/_authed/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthedShiftsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales': {
      id: '/_authed/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthedSalesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rota': {
      id: '/_authed/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthedRotaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my': {
      id: '/_authed/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthedMyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/menu': {
      id: '/_authed/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthedMenuRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/insights': {
      id: '/_authed/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedInsightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthedPeopleIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/$memberId': {
      id: '/_authed/people/$memberId'
      path: '/people/$memberId'
      fullPath: '/people/$memberId'
      preLoaderRoute: typeof AuthedPeopleMemberIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedInsightsRoute: typeof AuthedInsightsRoute
  AuthedMenuRoute: typeof AuthedMenuRoute
  AuthedMyRoute: typeof AuthedMyRoute
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedRotaRoute: typeof AuthedRotaRoute
  AuthedSalesRoute: typeof AuthedSalesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShiftsRoute: typeof AuthedShiftsRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedWarehouseRoute: typeof AuthedWarehouseRoute
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPeopleMemberIdRoute: typeof AuthedPeopleMemberIdRoute
  AuthedPeopleIndexRoute: typeof AuthedPeopleIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedInsightsRoute: AuthedInsightsRoute,
  AuthedMenuRoute: AuthedMenuRoute,
  AuthedMyRoute: AuthedMyRoute,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedRotaRoute: AuthedRotaRoute,
  AuthedSalesRoute: AuthedSalesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShiftsRoute: AuthedShiftsRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedWarehouseRoute: AuthedWarehouseRoute,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPeopleMemberIdRoute: AuthedPeopleMemberIdRoute,
  AuthedPeopleIndexRoute: AuthedPeopleIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ClockQrTokenRoute: ClockQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
