/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as ClockQrTokenRouteImport } from './routes/clock.$qrToken'
import { Route as AuthedStockRouteImport } from './routes/_authed.stock'
import { Route as AuthedShiftsRouteImport } from './routes/_authed.shifts'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedSalesRouteImport } from './routes/_authed.sales'
import { Route as AuthedMyRouteImport } from './routes/_authed.my'
import { Route as AuthedMenuRouteImport } from './routes/_authed.menu'
import { Route as AuthedPeopleIndexRouteImport } from './routes/_authed.people.index'
import { Route as AuthedPeopleMemberIdRouteImport } from './routes/_authed.people.$memberId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ClockQrTokenRoute = ClockQrTokenRouteImport.update({
  id: '/clock/$qrToken',
  path: '/clock/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShiftsRoute = AuthedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSalesRoute = AuthedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRoute = AuthedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMenuRoute = AuthedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleIndexRoute = AuthedPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleMemberIdRoute = AuthedPeopleMemberIdRouteImport.update({
  id: '/people/$memberId',
  path: '/people/$memberId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/menu': typeof AuthedMenuRoute
  '/my': typeof AuthedMyRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/stock': typeof AuthedStockRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/menu': typeof AuthedMenuRoute
  '/my': typeof AuthedMyRoute
  '/sales': typeof AuthedSalesRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/stock': typeof AuthedStockRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/': typeof AuthedIndexRoute
  '/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/people': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/menu': typeof AuthedMenuRoute
  '/_authed/my': typeof AuthedMyRoute
  '/_authed/sales': typeof AuthedSalesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/shifts': typeof AuthedShiftsRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/clock/$qrToken': typeof ClockQrTokenRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/people/$memberId': typeof AuthedPeopleMemberIdRoute
  '/_authed/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/menu'
    | '/my'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/stock'
    | '/clock/$qrToken'
    | '/people/$memberId'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/menu'
    | '/my'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/stock'
    | '/clock/$qrToken'
    | '/'
    | '/people/$memberId'
    | '/people'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/menu'
    | '/_authed/my'
    | '/_authed/sales'
    | '/_authed/settings'
    | '/_authed/shifts'
    | '/_authed/stock'
    | '/clock/$qrToken'
    | '/_authed/'
    | '/_authed/people/$memberId'
    | '/_authed/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClockQrTokenRoute: typeof ClockQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/clock/$qrToken': {
      id: '/clock/$qrToken'
      path: '/clock/$qrToken'
      fullPath: '/clock/$qrToken'
      preLoaderRoute: typeof ClockQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shifts': {
      id: '/_authed/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthedShiftsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sales': {
      id: '/_authed/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthedSalesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my': {
      id: '/_authed/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthedMyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/menu': {
      id: '/_authed/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthedMenuRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthedPeopleIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/$memberId': {
      id: '/_authed/people/$memberId'
      path: '/people/$memberId'
      fullPath: '/people/$memberId'
      preLoaderRoute: typeof AuthedPeopleMemberIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMenuRoute: typeof AuthedMenuRoute
  AuthedMyRoute: typeof AuthedMyRoute
  AuthedSalesRoute: typeof AuthedSalesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShiftsRoute: typeof AuthedShiftsRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPeopleMemberIdRoute: typeof AuthedPeopleMemberIdRoute
  AuthedPeopleIndexRoute: typeof AuthedPeopleIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMenuRoute: AuthedMenuRoute,
  AuthedMyRoute: AuthedMyRoute,
  AuthedSalesRoute: AuthedSalesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShiftsRoute: AuthedShiftsRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPeopleMemberIdRoute: AuthedPeopleMemberIdRoute,
  AuthedPeopleIndexRoute: AuthedPeopleIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ClockQrTokenRoute: ClockQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
